
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author NandiniCreations
 */
public class Task2_Number_Guessing extends javax.swing.JFrame {

    /**
     * Creates new form Task2_Number_Guessing
     */
    static int gen_num = 0;
    static int attempts = 10;
    static int score = 0;

    public Task2_Number_Guessing() {
        initComponents();

        main_label.setVisible(true);
        guess_label.setVisible(true);
        guess_tf.setVisible(true);
        submit_button.setVisible(true);
        hl_display_label.setVisible(true);
        attempts_label.setVisible(true);
        attempts_tf.setVisible(true);
        score_label.setVisible(true);

        attempts_tf.setEditable(false);
        attempts_tf.setText("10");
        hl_display_label.setText("");
        score_label.setText("" + score);

        generate();
    }

    static void generate() {
        gen_num = (int) (Math.random() * (100 - 0 + 1) + 0);
        //System.out.println(gen_num);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_Panel = new javax.swing.JPanel();
        main_label = new javax.swing.JLabel();
        guess_label = new javax.swing.JLabel();
        guess_tf = new javax.swing.JTextField();
        hl_display_label = new javax.swing.JLabel();
        submit_button = new javax.swing.JButton();
        attempts_label = new javax.swing.JLabel();
        attempts_tf = new javax.swing.JTextField();
        score_label = new javax.swing.JLabel();
        tryAgain_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        main_label.setText("Number Guessing Game");
        main_Panel.add(main_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 16, -1, -1));

        guess_label.setText("Enter your Guess :");
        main_Panel.add(guess_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 73, -1, -1));
        main_Panel.add(guess_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 109, -1));

        hl_display_label.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        hl_display_label.setForeground(new java.awt.Color(255, 255, 255));
        hl_display_label.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "YOUR GUESS IS ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N
        main_Panel.add(hl_display_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 110, 290, 90));

        submit_button.setText("SUBMIT");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });
        main_Panel.add(submit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        attempts_label.setText("Number of attempts left :");
        main_Panel.add(attempts_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 220, -1, -1));
        main_Panel.add(attempts_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 217, 90, -1));

        score_label.setBackground(new java.awt.Color(102, 102, 102));
        score_label.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        score_label.setForeground(new java.awt.Color(0, 255, 255));
        score_label.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Final Score", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N
        main_Panel.add(score_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 257, 210, 80));

        tryAgain_button.setText("TRY AGAIN");
        tryAgain_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryAgain_buttonActionPerformed(evt);
            }
        });
        main_Panel.add(tryAgain_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 365, -1, -1));

        exit_button.setText("EXIT");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        main_Panel.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 365, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        int find = 0;
        int guess = Integer.parseInt(guess_tf.getText());
        if (attempts > 0) {
            if (guess == gen_num) {
                hl_display_label.setText("PERFECT");
                find = 1;
            } else if (guess > gen_num) {
                hl_display_label.setText("HIGHER");
                attempts--;
                attempts_tf.setText("" + attempts);
            } else {
                hl_display_label.setText("LOWER");
                attempts--;
                attempts_tf.setText("" + attempts);
            }
        }

        if (find == 1 && attempts > 0) {
            score = attempts * 10;
            score_label.setText("" + score);
            JOptionPane.showMessageDialog(this, "Congratulations, your score is " + score);
        } else if(attempts <= 0) {
            JOptionPane.showMessageDialog(this, "Sorry. Ran out of Attempts\nThe number was "+gen_num);
            System.exit(0);
        }


    }//GEN-LAST:event_submit_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void tryAgain_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryAgain_buttonActionPerformed
        // TODO add your handling code here:
        guess_tf.setText("");
        attempts_tf.setEditable(false);
        attempts_tf.setText("10");
        score_label.setText("0");

        hl_display_label.setText("");

        attempts = 10;
        score = 0;
        generate();

    }//GEN-LAST:event_tryAgain_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Task2_Number_Guessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Task2_Number_Guessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Task2_Number_Guessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Task2_Number_Guessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task2_Number_Guessing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attempts_label;
    private javax.swing.JTextField attempts_tf;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel guess_label;
    private javax.swing.JTextField guess_tf;
    private javax.swing.JLabel hl_display_label;
    private javax.swing.JPanel main_Panel;
    private javax.swing.JLabel main_label;
    private javax.swing.JLabel score_label;
    private javax.swing.JButton submit_button;
    private javax.swing.JButton tryAgain_button;
    // End of variables declaration//GEN-END:variables
}
